### ISSUE TITLE
Microsoft.Data.SqlClient for .NET Framework

### ISSUE THREAD

**Issue by njones57** [RickStrahl/Westwind.Utilities#23]
I see that in #15 that a commit was made to support using the Microsoft.Data.SqlClient  but only for .NET Core. The project I'm currently working on utilized Westwind in .NET Framework 4.8.1 but is migrating to using Azure SQL Servers via Azure Active Directory authentication. It is currently not able to pull translations from the database due to this. Is there a way to enable the Microsoft.Data.SqlClient  for .NET Framework?

**Comment by RickStrahl** [comment]
The problem with this is that it changes the deployment requirements by pulling in a bunch of the dependencies for NETFX.

I've been very reluctant to do this because if this as this is a sizable chunk of files that gets added to each deployed app. In Core this is not an issue as these libraries are part of the runtime.

May revisit this in the future now that Westwind.Utilities.Data is a separate package to at least remove the dependencies when not using data access.

**Comment by RickStrahl** [comment]
Implemented with separation of Westwind.Utilities.Data some time ago.
