### ISSUE TITLE
UrlEncodingParser doesn't allow null values

### ISSUE THREAD

**Issue by DaveSweeton** [RickStrahl/Westwind.Utilities#24]
We're using UrlEncodingParser as a replacement for HttpUtility.ParseQueryString (thank you!). One difference we've noticed is that when calling ToString on the returned NameValueCollection is that it throws exceptions when a value is null, unlike the System.Web implementation.

```
System.ArgumentNullException : Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at Westwind.Utilities.UrlEncodingParser.ToString() in D:\projects\Westwind.Utilities\Westwind.Utilities\SupportClasses\UrlEncodingParser.cs:line 132
```

**Comment by DaveSweeton** [comment]
It's an easy fix, I'm happy to submit a PR!

**Comment by DaveSweeton** [comment]
Thanks! No, it was adding a null value after parse: query["name"] = null,
then using query.ToString().

-Dave

**Comment by RickStrahl** [comment]
Ah Ok. Ok that's fixed too 😀

**Comment by RickStrahl** [comment]
Actually I wonder if the value is null the key probably shouldn't be there at all. Empty too? Maybe not there with null, but there but empty with string.empty.

**Comment by DaveSweeton** [comment]
I think with the system.web version the key is present and the value is
empty: ?name=&id=26

-Dave

**Comment by RickStrahl** [comment]
Yeah I can handle that in parsing, but if you put an explicit null into the an indexer you're going to get it back. 

But that actually does answer my question. I can handle the parse but I have to know that the value exists in order to return it in the collection. So it has to be there - otherwise the indexer will fail and I can't control that.

I wrote this so long ago, and it was definitely not the greatest idea to subclass NVC :smile:

**Comment by RickStrahl** [comment]
Thinking this over the only fix that's really needed is this:

```cs
        /// <summary>
        /// override indexer to ensure we always non-null value
        /// </summary>
        public string this[string key]
        {
            get
            {
                return base[key] ?? string.Empty;                
            }
            set
            {
                base[key] = value ?? string.Empty;
            }
        }
```

This ensures that:

* Null values are always fixed up on the way in and out
* Missing values also return string.empty

**Comment by DaveSweeton** [comment]
That probably works for my situation, but I wonder if it would be better to
check for null before calling System.Uri.EscapeDataString? That way you get
back what you put in via the indexer, but ToString returns the expected
result.

**Comment by RickStrahl** [comment]
The value can never be null now because the assignment now ensures that it won't be and the parser always sets a non-null value anyway.

I had that code initially but it didn't address the null value when:

* returning a null value explicitly set into the collection (ie. not parsed)
* returning a null value when returning a bogus key

The indexer addresses all those scenarios.

**Comment by DaveSweeton** [comment]
Sounds good! My main scenario was to build a string value, so my code
didn't read from the indexer.
