### ISSUE TITLE
XPathException: Expression must evaluate to a node-set

### ISSUE THREAD

**Issue by M-Habbi** [RickStrahl/Westwind.Utilities#9]
When setting the ConfigurationFile property of a ConfigurationFileConfigurationProvider object, leaving out the ConfigurationSection property, I get the following error at runtime, as soon as I try to access a property of my custom AppConfiguration class: "XPathException: Expression must evaluate to a node-set." When I set the ConfigurationSection property it works.
I just want to save the config file in a different directory, I don't expect to have to provide a ConfigurationSection value.

**Comment by RickStrahl** [comment]
The configuration section is a key part of the XML Configuration format, so yes that's not optional.

I'm not sure by what you mean on just save. In order to use it you'd have to load first unless you get default settings. And even then in order to save you need the configuration sections - without it where would it save?

**Comment by M-Habbi** [comment]
I agree. I was just thrown off by the error message. Personally, I don't care about the config section name, that's why I left it out. Now that I know the background, I just provide a custom default value.

But I recommend you handling this particular exception that tells you to also provide a config section name if you specify the file name. I am sure I'm not the only one trying to take the easy way out.
